// Code generated by mockery v2.45.1. DO NOT EDIT.

package ws

import mock "github.com/stretchr/testify/mock"

// MockMessageMatcher is an autogenerated mock type for the MessageMatcher type
type MockMessageMatcher struct {
	mock.Mock
}

// MatchMessage provides a mock function with given fields: _a0
func (_m *MockMessageMatcher) MatchMessage(_a0 Message) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for MatchMessage")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(Message) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewMockMessageMatcher creates a new instance of MockMessageMatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageMatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageMatcher {
	mock := &MockMessageMatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
